### PR TITLE
Add more companies in the crypto, fintech, and trading category

### PR DESCRIPTION
**Pull request by chao1995**

### CODE REVIEW

**Comment by paradite** [comment]
There is a note on banks and non-tech companies on top:

> Note Banks and non-tech companies are intentionally omitted from the list.

I think you can remove some of them and leave the tech trading firms.

**Comment by chao1995** [comment]
Sorry, didn't notice that. Will do. Though I think Singapore made its fortune through trading (the old-fashioned, but still classic, import/export of goods type of business) and then become a finance hub due to the need of FX etc.. It has become a very successful financial hub ever since, now ranking just behind New York and London in 2022. And given the lay-offs in the tech industry at the moment, it makes sense to include them since they are still hiring..

**Comment by paradite** [comment]
Yes. Please remove non-tech companies. Also please do not edit things other than the actual list, for example, introduction paragraph.

**Comment by chao1995** [comment]
Ok sure, will do later tonight. Thanks!

**Comment by paradite** [comment]
Thank you. I have verified that all the companies have open positions or engineering presence in Singapore.

Merged.

**Pull request merged**
